### ISSUE TITLE
nginx-log-exporter binary does not work

### ISSUE THREAD

**Issue by manukoli1986** [songjiayang/nginx-log-exporter#1]
# ./nginx-log-exporter-0.1.linux-386
-bash: ./nginx-log-exporter-0.1.linux-386: cannot execute binary file

I have tried different versions but this binary is not executing. Can you please look into it. 
OR 
How can we build it by own. Please suggest.

**Comment by songjiayang** [comment]
What's your `OS` version? you can tell me the details then I can build one for you.

You also can install Golang with link https://golang.org/dl then build yourself with command  `go build -o nginx-log-exporter main.go ` .

**Comment by manukoli1986** [comment]
OS version: centos7 and i have created the binary using the same command understating the go lang. I created the binary but now the issue is how can I pass the argument using the binary file. 

Please check below issue.
[root@centos7~]# /usr/bin/nginx-log-exporter  -config-file /etc/config2.yaml
flag provided but not defined: -config-file
Usage of /usr/bin/nginx-log-exporter:
  -config.file string
        Nginx log exporter configuration file name. (default "config.yml")
  -web.listen-address string
        Address to listen on for the web interface and API. (default ":9999")

I believe I did not define the flag during binary generation. 
I used the same command:
go build -o /path/nginx-log-exporter

**Comment by manukoli1986** [comment]
And also can we use regex for querying.
i.e.  I only need "/v1.0/example". How can we get this only..
app_http_response_time_seconds_sum{foo="foo",method="GET",request="/v1.0/example/:id",status="200"} 0.003

Do we need to configure the config.yml file because we have many different requests which we receive and I want to monitor them all but only "/v1.0/XXX" this much part.

**Comment by Yzzzi** [comment]
same, CentOS 7; cannot execute binary file

**Comment by patsevanton** [comment]
cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

./nginx-log-exporter-0.1.linux-amd64 
-bash: ./nginx-log-exporter-0.1.linux-amd64: cannot execute binary file

**Comment by songjiayang** [comment]
sorry, fixed, please download new one and try again.
