### ISSUE TITLE
relabel支持占位符

### ISSUE THREAD

**Issue by shengbinxu** [songjiayang/nginx-log-exporter#8]
谢谢你的工作，我已经用到我的项目中了。
同时，我增加了一个feature，麻烦帮忙看下是否接受该feature。

问题场景：
微服务架构下，所有的流量都会先到nginx网关，日志中的request url格式如下

/api/service1/path1/123/xxx
/api/serivice2/path1/456/xxx
/api/serivice2/path1/path2/456/xxx
/api/serivice3/path1/path2/path3/456/xxx

需求：

1. url中的"service"代表的是微服务的名称，因此呢，就想提取出service，把sevice作为prometheus的一个label
2. 把url中的数字，替换成固定的字符。目前的替换不是很方便，无法在一个配置中把所有为数字的路径统一进行替换。

针对这两点，我做了改进，代码如下：
https://github.com/songjiayang/nginx-log-exporter/commit/8bb6788c98bc49a1b8ea5e6943275ffccde6986f

metrics如下：
gateway_service_http_response_count_total{method="GET",region="zone1",service="data-api",status="200"} 3357
gateway_service_http_response_count_total{method="GET",region="zone1",service="data-api",status="4xx"} 12
gateway_service_http_response_count_total{method="GET",region="zone1",service="data-api",status="5xx"} 173
gateway_service_http_response_count_total{method="GET",region="zone1",service="data-apier",status="200"} 3592
gateway_service_http_response_count_total{method="GET",region="zone1",service="data-apier",status="4xx"} 119
gateway_service_http_response_count_total{method="GET",region="zone1",service="data-apier",status="5xx"} 728
gateway_service_http_response_count_total{method="GET",region="zone1",service="device",status="200"} 40449
gateway_service_http_response_count_total{method="GET",region="zone1",service="device",status="4xx"} 10
gateway_service_http_response_count_total{method="GET",region="zone1",service="device",status="5xx"} 314

gateway_uri_http_response_count_total{method="GET",region="zone1",status="200",uri="/api-customer/device/:id/trackDetail"} 742
gateway_uri_http_response_count_total{method="GET",region="zone1",status="200",uri="/api-customer/device/:id/workAttendanceDetail"} 739
gateway_uri_http_response_count_total{method="GET",region="zone1",status="200",uri="/api-customer/device/entity/:id/historyData"} 1
gateway_uri_http_response_count_total{method="GET",region="zone1",status="200",uri="/api-customer/device/entity/:id/locsByTime"} 2
gateway_uri_http_response_count_total{method="GET",region="zone1",status="200",uri="/api-customer/device/entity/:id/search"} 712

麻烦审阅，如觉得该feature有价值，我再润色下，补充下readme之类的，提交pull request

**Comment by songjiayang** [comment]
感谢您的PR，非常不错的 idea，我们尽量保持原有的配置样例不变，所以有一些小的修改建议：

1. 是否方便在 logs 下面新增您这个case 的日志样例。
2. config.yml 中可以新增一个 app 用于您这个case 修改。

可以提交一个正式的 PR，我们再看看如何完善相关测试，再次感谢。

**Comment by shengbinxu** [comment]
@songjiayang ok，收到，近期我完善之后提交PR
